In [1]:
import os
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from flask import Flask, request, jsonify

In [3]:
# Load the dataset
data = pd.read_csv('/content/drive/MyDrive/my_project/Salary_Data.csv')

print(data.columns)
data.head()
print(data.dtypes)
data.columns = data.columns.str.strip()

Index(['Age', 'Gender', 'Education_Level', 'Job', 'Years_of_Experience',
       'Salary'],
      dtype='object')
Age                    float64
Gender                  object
Education_Level         object
Job                     object
Years_of_Experience    float64
Salary                 float64
dtype: object


In [4]:
print(data.columns)


Index(['Age', 'Gender', 'Education_Level', 'Job', 'Years_of_Experience',
       'Salary'],
      dtype='object')


In [5]:
# Assuming df is your DataFrame
if 'job' in data.columns:
    print(data['job'])
else:
    print("'Job' key does not exist in the DataFrame")

'Job' key does not exist in the DataFrame


In [6]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

df = pd.read_csv('/content/drive/MyDrive/my_project/Salary_Data.csv')
job_column = df['Job']
le = LabelEncoder()
df['Job_num'] = le.fit_transform(job_column)
df = df.drop(columns=['Job'])

print(df)

      Age  Gender Education_Level  Years_of_Experience    Salary  Job_num
0    32.0    Male      Bachelor's                  5.0   90000.0      159
1    28.0  Female        Master's                  3.0   65000.0       17
2    45.0    Male             PhD                 15.0  150000.0      130
3    36.0  Female      Bachelor's                  7.0   60000.0      101
4    52.0    Male        Master's                 20.0  200000.0       22
..    ...     ...             ...                  ...       ...      ...
370  35.0  Female      Bachelor's                  8.0   85000.0      131
371  43.0    Male        Master's                 19.0  170000.0       30
372  29.0  Female      Bachelor's                  2.0   40000.0       70
373  34.0    Male      Bachelor's                  7.0   90000.0      137
374  44.0  Female             PhD                 15.0  150000.0      110

[375 rows x 6 columns]


In [7]:
job_column = df['Gender']
le = LabelEncoder()
df['GEN'] = le.fit_transform(job_column)
df = df.drop(columns=['Gender'])

print(df)

      Age Education_Level  Years_of_Experience    Salary  Job_num  GEN
0    32.0      Bachelor's                  5.0   90000.0      159    1
1    28.0        Master's                  3.0   65000.0       17    0
2    45.0             PhD                 15.0  150000.0      130    1
3    36.0      Bachelor's                  7.0   60000.0      101    0
4    52.0        Master's                 20.0  200000.0       22    1
..    ...             ...                  ...       ...      ...  ...
370  35.0      Bachelor's                  8.0   85000.0      131    0
371  43.0        Master's                 19.0  170000.0       30    1
372  29.0      Bachelor's                  2.0   40000.0       70    0
373  34.0      Bachelor's                  7.0   90000.0      137    1
374  44.0             PhD                 15.0  150000.0      110    0

[375 rows x 6 columns]


In [8]:
job_column = df['Education_Level']
le = LabelEncoder()
df['EDU'] = le.fit_transform(job_column)
df = df.drop(columns=['Education_Level'])

print(df)

      Age  Years_of_Experience    Salary  Job_num  GEN  EDU
0    32.0                  5.0   90000.0      159    1    0
1    28.0                  3.0   65000.0       17    0    1
2    45.0                 15.0  150000.0      130    1    2
3    36.0                  7.0   60000.0      101    0    0
4    52.0                 20.0  200000.0       22    1    1
..    ...                  ...       ...      ...  ...  ...
370  35.0                  8.0   85000.0      131    0    0
371  43.0                 19.0  170000.0       30    1    1
372  29.0                  2.0   40000.0       70    0    0
373  34.0                  7.0   90000.0      137    1    0
374  44.0                 15.0  150000.0      110    0    2

[375 rows x 6 columns]


In [10]:
# Assume df is your DataFrame with the 'Age' column
df['Age'].fillna(df['Age'].median(), inplace=True)

In [11]:
# Assume df is your DataFrame with the 'Age' column
df['Years_of_Experience'].fillna(df['Years_of_Experience'].mean(), inplace=True)

In [9]:
# Assume df is your DataFrame with the 'Age' column
df['Salary'].fillna(df['Salary'].mean(), inplace=True)

# Assume df is your DataFrame with the 'Age' column
df['Job_num'].fillna(df['Job_num'].mode(), inplace=True)

# Assume df is your DataFrame with the 'Age' column
df['GEN'].fillna(df['GEN'].mode(), inplace=True)

# Assume df is your DataFrame with the 'Age' column
df['EDU'].fillna(df['EDU'].mean(), inplace=True)

In [12]:
# Outlier detection and treatment
Q1 = df.quantile(0.25)
Q3 = df.quantile(0.75)
IQR = Q3 - Q1
df = df[~((df < (Q1 - 1.5 * IQR)) | (df > (Q3 + 1.5 * IQR))).any(axis=1)]
print(df)

      Age  Years_of_Experience    Salary  Job_num  GEN  EDU
0    32.0                  5.0   90000.0      159    1    0
1    28.0                  3.0   65000.0       17    0    1
2    45.0                 15.0  150000.0      130    1    2
3    36.0                  7.0   60000.0      101    0    0
4    52.0                 20.0  200000.0       22    1    1
..    ...                  ...       ...      ...  ...  ...
370  35.0                  8.0   85000.0      131    0    0
371  43.0                 19.0  170000.0       30    1    1
372  29.0                  2.0   40000.0       70    0    0
373  34.0                  7.0   90000.0      137    1    0
374  44.0                 15.0  150000.0      110    0    2

[373 rows x 6 columns]


In [13]:
# Assuming your dataset is a pandas dataframe named 'df' and it has predictor variables ['var1', 'var2', 'var3'] and target variable 'target'
from sklearn.model_selection import train_test_split

X = df[['Years_of_Experience', 'Age', 'Job_num','GEN','EDU']].values
y = df['Salary'].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [14]:
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

# feature scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# imputing missing values (if any)
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer = imputer.fit(X_train)
X_train = imputer.transform(X_train)
X_test = imputer.transform(X_test)

In [15]:
from sklearn.linear_model import LogisticRegression

# for example, we use logistic regression
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [16]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# make predictions
y_pred = model.predict(X_test)

# evaluate performance
print(f"Accuracy: {accuracy_score(y_test, y_pred)}")
print(f"Confusion Matrix: \n{confusion_matrix(y_test, y_pred)}")
print(f"Classification Report: \n{classification_report(y_test, y_pred)}")

Accuracy: 0.28
Confusion Matrix: 
[[0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 9 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 4 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 3 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 5 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 2 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 1 0 0

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [17]:
#!pip install matplotlib-venn
#!pip install cartopy
import joblib
import pickle
from sklearn.ensemble import RandomForestRegressor

# Define the path where the model will be stored
model_path = 'models/my_model.pkl'

# Save the model to the defined path
with open(model_path, 'wb') as f:
    pickle.dump(clf, f)


# assuming your trained model is called rf
joblib.dump(df, 'model.pkl')

#joblib.dump(model, 'my_model.pkl')

['model.pkl']